service:
  protocol: "http"
  host: "localhost"
  port: 8080
  media-root: "./media/"
  media-url: "/media/"
  db:
    engine: "postgres"
    dbname: "golang"
    host: "db"
    port: "5432"
    username: "postgres"
    password: "postgres"
